import com.gnostice.pdfone.PDFOne;
import com.gnostice.pdfone.PdfDocument;
import com.gnostice.pdfone.PdfException;
import com.gnostice.pdfone.PdfReader;
import java.io.IOException;
import javax.swing.JOptionPane;

    import java.awt.Font;
    import java.text.DateFormat;
    import java.text.SimpleDateFormat;
    import javax.swing.JFrame;
    import javax.swing.JLabel;
    import javax.swing.JPanel;
/*
 * ViewerFrame.java
 *
 * Created on november 14, 2012, 7:54 PM
 */

/**
 *
 * @author  anupom mondol
 */
public class ViewerFrame extends javax.swing.JFrame {
   
   
    public ViewerFrame() {
        initComponents();
        setTitle("AM PDF Viewer");
        getContentPane().add(jp());
        getContentPane().add(jp2());
        frm2.setVisible(false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frm2 = new javax.swing.JFrame();
        fc = new javax.swing.JFileChooser();
        viewer = new com.gnostice.pdfone.PdfViewer();
        jToolBar1 = new javax.swing.JToolBar();
        btnLoad = new javax.swing.JButton();
        btnFirstPage = new javax.swing.JButton();
        btnPreviousPage = new javax.swing.JButton();
        btnNextPage = new javax.swing.JButton();
        btnLastPage = new javax.swing.JButton();
        zoomin = new javax.swing.JButton();
        zoomout = new javax.swing.JButton();
        jp = new javax.swing.JPanel();
        jp2 = new javax.swing.JPanel();
        jdate = new javax.swing.JLabel();
        jtime = new javax.swing.JLabel();

        fc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout frm2Layout = new org.jdesktop.layout.GroupLayout(frm2.getContentPane());
        frm2.getContentPane().setLayout(frm2Layout);
        frm2Layout.setHorizontalGroup(
            frm2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, frm2Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(fc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        frm2Layout.setVerticalGroup(
            frm2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, frm2Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(fc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        viewer.setBackgroundColor(new java.awt.Color(205, 204, 197));

        jToolBar1.setBorder(null);

        btnLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NextPage.gif"))); // NOI18N
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLoad);

        btnFirstPage.setText("First Page");
        btnFirstPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstPageActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFirstPage);

        btnPreviousPage.setText("Previous Page");
        btnPreviousPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousPageActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPreviousPage);

        btnNextPage.setText("Next Page");
        btnNextPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextPageActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNextPage);

        btnLastPage.setText("Last Page");
        btnLastPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastPageActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLastPage);

        zoomin.setText("Zoom In");
        zoomin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoominActionPerformed(evt);
            }
        });

        zoomout.setText("Zoom Out");
        zoomout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoomoutActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jpLayout = new org.jdesktop.layout.GroupLayout(jp);
        jp.setLayout(jpLayout);
        jpLayout.setHorizontalGroup(
            jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 104, Short.MAX_VALUE)
        );
        jpLayout.setVerticalGroup(
            jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
        );

        jtime.setBackground(new java.awt.Color(255, 255, 204));

        org.jdesktop.layout.GroupLayout jp2Layout = new org.jdesktop.layout.GroupLayout(jp2);
        jp2.setLayout(jp2Layout);
        jp2Layout.setHorizontalGroup(
            jp2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jp2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jtime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jdate, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );
        jp2Layout.setVerticalGroup(
            jp2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jdate, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
            .add(jtime, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jToolBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 558, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(zoomin)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(zoomout)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jp2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(viewer, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jp2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jToolBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(zoomin)
                        .add(zoomout))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(viewer, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLastPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastPageActionPerformed
// TODO add your handling code here:
        try {
            viewer.lastPage();
        } catch(PdfException pdfe) {
            JOptionPane.showMessageDialog(this, pdfe.getMessage(), "AM PDF Viewer",
                    JOptionPane.ERROR_MESSAGE);
        } catch(IOException ioe) {
            JOptionPane.showMessageDialog(this, ioe.getMessage(), "AM PDF Viewer",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLastPageActionPerformed

    private void btnNextPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextPageActionPerformed
// TODO add your handling code here:
        try {
            viewer.nextPage();
        } catch(PdfException pdfe) {
            JOptionPane.showMessageDialog(this, pdfe.getMessage(), "AM PDF Viewer",
                    JOptionPane.ERROR_MESSAGE);
        } catch(IOException ioe) {
            JOptionPane.showMessageDialog(this, ioe.getMessage(), "AM PDF Viewer",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnNextPageActionPerformed

    private void btnPreviousPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousPageActionPerformed
// TODO add your handling code here:
        try {
            viewer.previousPage();
        } catch(PdfException pdfe) {
            JOptionPane.showMessageDialog(this, pdfe.getMessage(), "AM PDF Viewer",
                    JOptionPane.ERROR_MESSAGE);
        } catch(IOException ioe) {
            JOptionPane.showMessageDialog(this, ioe.getMessage(), "AM PDF Viewer",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPreviousPageActionPerformed
    
    private void btnFirstPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstPageActionPerformed
// TODO add your handling code here:
        try {
            viewer.firstPage();
        } catch(PdfException pdfe) {
            JOptionPane.showMessageDialog(this, pdfe.getMessage(), "AM PDF Viewer",
                    JOptionPane.ERROR_MESSAGE);
        } catch(IOException ioe) {
            JOptionPane.showMessageDialog(this, ioe.getMessage(), "AM PDF Viewer",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnFirstPageActionPerformed
        
    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
// TODO add your handling code here:
        frm2.setVisible(true);
        frm2.setBounds(0, 0, 600, 400);
        frm2.setTitle("Choose a pdf file - AM pdf reader");
    }//GEN-LAST:event_btnLoadActionPerformed

    private void zoominActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoominActionPerformed
        // TODO add your handling code here:
        try{
            viewer.zoomIn();
        }catch(PdfException pdfEx) {
            JOptionPane.showMessageDialog(this, pdfEx.getMessage(), "AM PDF Viewer",
                    JOptionPane.ERROR_MESSAGE);
            setTitle("AM PDF Viewer");
        }
    }//GEN-LAST:event_zoominActionPerformed

    private void zoomoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoomoutActionPerformed
        // TODO add your handling code here:
        try{
            viewer.zoomOut();
        }catch(PdfException pdfEx) {
            JOptionPane.showMessageDialog(this, pdfEx.getMessage(), "AM PDF Viewer",
                    JOptionPane.ERROR_MESSAGE);
            setTitle("AM PDF Viewer");
        }
    }//GEN-LAST:event_zoomoutActionPerformed

    private void fcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcActionPerformed
        // TODO add your handling code here:
        try {
            r = PdfReader.fileReader(fc.getSelectedFile());
            d = new PdfDocument(r);

            viewer.loadDocument(d);

            setTitle(fc.getSelectedFile() + " - AM PDF Viewer");

        } catch (PdfException pdfEx) {
            JOptionPane.showMessageDialog(this, pdfEx.getMessage(), "AM PDF Viewer",
                    JOptionPane.ERROR_MESSAGE);
            setTitle("AM PDF Viewer");
        } catch (IOException ioEx) {
            JOptionPane.showMessageDialog(this, ioEx.getMessage(), "AM PDF Viewer",
                    JOptionPane.ERROR_MESSAGE);
            setTitle("AM PDF Viewer");
        }
        frm2.setVisible(false);
    }//GEN-LAST:event_fcActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewerFrame().setVisible(true);
            }
        });
    }
    DateFormat dateFormat2 = new SimpleDateFormat("h:mm:ss a");
        java.util.Date date2;
    public JPanel jp(){
            Font f;
            f = new Font("SansSerif", Font.PLAIN, 15);                 
            jtime= new JLabel("");
            updateDateTime();
            jtime.setBounds(0,0,200,30);
            jtime.setFont(f);
            jp.add(jtime);


       
            return jp ;
        }
    public void updateDateTime()
        {
        Thread th = new Thread(new Runnable()
            {
            public void run()
                {
                while(true)
                    {
                    date2 = new java.util.Date();
                    String dateTime = dateFormat2.format(date2);
                    jtime.setText(dateTime);
                    jtime.updateUI();
                    }
                }
            });
        th.start();
        }
    public JPanel jp2()
   {
       Font f;
       f = new Font("SansSerif", Font.PLAIN, 15);
       
       DateFormat dateFormat = new SimpleDateFormat("EEEEEEEEE: dd MMM, yyyy.");
       java.util.Date date = new java.util.Date();
       String dateTime = dateFormat.format(date);
       
       jdate = new JLabel(dateTime);   
       jdate.setBounds(0, 0, 200, 30);  
       jdate.setFont(f);
       jp2.add(jdate);
       
       return jp2;
   }
    
    PdfDocument d;
    PdfReader r;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirstPage;
    private javax.swing.JButton btnLastPage;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnNextPage;
    private javax.swing.JButton btnPreviousPage;
    private javax.swing.JFileChooser fc;
    private javax.swing.JFrame frm2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel jdate;
    private javax.swing.JPanel jp;
    private javax.swing.JPanel jp2;
    private javax.swing.JLabel jtime;
    private com.gnostice.pdfone.PdfViewer viewer;
    private javax.swing.JButton zoomin;
    private javax.swing.JButton zoomout;
    // End of variables declaration//GEN-END:variables
    
}
